name: what_when_where
description: What? When? Where?

version: 2.2.2+20202

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  audioplayers: ^0.15.1
  auto_size_text: ^2.1.0
  app_review: ^1.1.2
  cached_network_image: ^2.2.0+1
  dartx: ^0.4.1
  dio: ^3.0.9
  firebase_analytics: ^5.0.14
  firebase_crashlytics: ^0.1.3+3
  flutter_rating_bar: ^3.0.1+1
  flutter_redux: ^0.6.0
#  flutter_staggered_grid_view: ^0.3.0
  flutter_staggered_grid_view:
    git:
      url: https://github.com/BertrandBev/flutter_staggered_grid_view.git
  flutter_svg: ^0.17.4
  flutter_vibrate: ^1.0.0
  flutter_widget_from_html_core: ^0.3.3+4
  freezed_annotation: ^0.11.0+1
  get_it: ^4.0.2
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  html: ^0.14.0+3
  html_unescape: ^1.0.1+3
  i69n: ^1.1.0
  injectable: ^1.0.4
  isolate: ^2.0.3
  json_serializable: ^3.4.0
  path_provider: ^1.6.11
  photo_view: ^0.9.2
  rxdart: ^0.24.1
  share: ^0.6.4+3
  shared_preferences: ^0.5.7+3
  shimmer: ^1.1.1
  url_launcher: ^5.4.10
  xml2json: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.11.5
  hive_generator:
    git:
      url: git@github.com:hivedb/hive.git
      path: hive_generator
      ref: e90a7d940cc904eb335f35d59cca251cb810ae2d
  injectable_generator: ^1.0.4
  mockito: ^4.1.1
  extra_pedantic: ^1.2.0

dependency_overrides:
  path: 1.6.4
  analyzer: '0.39.14'

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family:  CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
